# Jupyter Book settings

title: Python Numérique
author: Valérie Roy & Thierry Parmentelat
logo: media/logo-python-numerique.svg

repository:
  url: https://github.com/ue12-p23/numerique
  branch: main
  path_to_book: notebooks

html:
  use_repository_button: yes
  use_edit_page_button: yes
  use_issues_button: yes
  favicon: media/logo-p23.svg

only_build_toc_files: true

exclude_patterns:
  - "**/.teacher/*"

execute:
  execute_notebooks: cache
  exclude_patterns:
    - "**/*-corrige*"
    - "**/.teacher/*"

parse:
  myst_enable_extensions:
    - html_image    # for raw <img> tags in markdown
    - dollarmath    # for mathjax
    - strikethrough

sphinx:
  config:
    nb_custom_formats:
      .py:
        - jupytext.reads
        - fmt: py:percent
    html_show_copyright: false
    # not quite convincing but...
    html_extra_path: ['media']
  extra_extensions:
    sphinx_exercise
