# update the jb toc from nbhosting
toc: ../.nbhosting/nbhosting.yaml

ifeq ($(TOCDIR),)
TOCDIR = notebooks
endif

# update nbhosting tracks from jupyter book toc
# need to prefix notebooks path with 'notebooks/'
../.nbhosting/nbhosting.yaml: _toc.yml
	$$HOME/git/nbhosting/scripts/jb-to-nbh-toc.py -p '$(TOCDIR)' $< $@
